### PR TITLE
SDK-455: Release v3.9.3

### LINKED ISSUE #70: Feature Request: Swift Package Manager Support
Please provide support for Swift Package Manager

### PR DESCRIPTION
**Pull request by Aditi3**
- Removes code related to Dynamic Variable and Visual Editor
- Adds support for installation via Swift Package Manager
- Refactored Utils and Device class
- Closes #70 & #103

### CODE REVIEW

**Comment by doublegucci** [comment]
I’m about to learn coding what do I need to download to get this too work?

**Review by akashvercetti — APPROVED** [review]

**Comment by iaagg** [comment]
@Aditi3 hello, thank you for a new version 🙌  
Will you be able to update Segment clevertap ios sdk soon to adopt a new 3.9.3 version?

**Comment by Aditi3** [comment]
@iaagg, Prepare CleverTap Segment iOS SDK for v3.9.3 is next up in my task list. I will try to do a release ASAP.

**Comment by iaagg** [comment]
@Aditi3 awesome, thank you! 🙏

**Pull request merged**
